FROM node:20-slim

WORKDIR /app

# Copy and install dependencies
COPY frontend/package.json frontend/bun.lockb* ./
RUN npm install

# Copy code
COPY frontend . 

# Expose dev/build port
EXPOSE 5173

# Run dev server
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
